volumes:
  db_data:

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress-base:
    image: wordpress:php8.3-fpm
    restart: always
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  server-base:
    image: nginx:latest
    restart: always
    depends_on:
      - wordpress-base

  wp:
    image: wordpress:cli
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    working_dir: /var/www/html
    entrypoint: ["wp"]

  composer:
    image: composer:latest
    working_dir: /app
    network_mode: "host"
