services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./:/var/www/html

  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - ./:/app

  cli:
    image: wpcli/wp-cli:latest
    depends_on:
      - wordpress
      - db
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: ["wp"]
    
volumes:
  db_data:
