services:
  db-glotpress:
    extends:
      file: common-services.yaml
      service: db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db-glotpress:/var/lib/mysql

  db-project:
    extends:
      file: common-services.yaml
      service: db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db-glotpress:/var/lib/mysql
      
  wordpress-glotpress:
    extends:
      file: common-services.yaml
      service: wordpress-base
    environment:
      WORDPRESS_DB_HOST: db-glotpress:3306
    depends_on:
      - db-glotpress
    volumes:
      - ./glotpress/wordpress:/var/www/html

  wordpress-project:
    extends:
      file: common-services.yaml
      service: wordpress-base
    environment:
      WORDPRESS_DB_HOST: db-project:3306
    depends_on:
      - db-project
    volumes:
      - ./project/wordpress:/var/www/html

  server-glotpress:
    extends:
      file: common-services.yaml
      service: server-base
    ports:
      - "80:80"
    volumes:
      - ./glotpress:/var/www/html

  server-project:
    extends:
      file: common-services.yaml
      service: server-base
    ports:
      - "8080:80"
    volumes:
      - ./project:/var/www/html

  wp-glotpress:
    extends:
      file: common-services.yaml
      service: wp
    depends_on:
      - wordpress-glotpress
      - db-glotpress
    volumes:
      - ./glotpress:/var/www/html

  wp-project:
    extends:
      file: common-services.yaml
      service: wp
    depends_on:
      - wordpress-project
      - db-project
    volumes:
      - ./project:/var/www/html

  composer-glotpress:
    extends:
      file: common-services.yaml
      service: composer
    volumes:
      - ./glotpress:/app

  composer-project:
    extends:
      file: common-services.yaml
      service: composer
    volumes:
      - ./project:/app

volumes:
  db-glotpress:
  db-project: